id: P006674
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1000
  title: ཞང་ཞུང་སྙན་རྒྱུད་ཀྱི་གསུང་པོད།
  author: ''
  volumes:
    a527d0c3ea284ddc9596bbb79473b79c:
      image_group_id: I1CZ1516
      title: ''
      volume_number: 1
      total_pages: 662
      base_file: v001.txt
